### PR TITLE
Add a package.json to use with npm/yarn

### PR DESCRIPTION
**Pull request by colinbellino**
Hi there.

I recently tried to use this package with yarn (https://yarnpkg.com/) but encountered an issue because a `package.json` file is required. I think this could help other people using npm or yarn so i made a PR for this.

Feel free to edit anything in the file as i used the default options for most things! ;)

### CODE REVIEW

**Comment by fu-raz** [comment]
I can't believe this hasn't been done yet. What year is it? 2010?

**Comment by xseano** [comment]
In an effort to bring back and expand this brilliant library created by EastDesire, I created [PaletteJS](https://github.com/xseano/PaletteJS). If it is not too much trouble, would you mind submitting this PR to PaletteJS? Please let me know if you would like to be added as a contributer as well. Thanks and let me know if you have any questions.

**Review by EastDesire — APPROVED** [review]

**Comment by EastDesire** [comment]
Merged. Sorry for the extreme delay, @cbellino.

**Comment by colinbellino** [comment]
No worries, i'm glad you were able to merge it :)

**Pull request merged**
