### PR TITLE
make pallete darker up to selected lightness

### PR DESCRIPTION
**Pull request by evgenjion**
Hi, I thought it would be nice, to have darker pallet up to set lightness. 

Here is the screenshot, how it looks like
colorpicker

### CODE REVIEW

**Comment by evgenjion** [comment]
@EastDesire could you look at pr?

**Comment by evgenjion** [comment]
@EastDesire ping

**Comment by xseano** [comment]
In an effort to bring back and expand this brilliant library created by EastDesire, I created [PaletteJS](https://github.com/xseano/PaletteJS). If it is not too much trouble, would you mind submitting this PR to PaletteJS? Please let me know if you would like to be added as a contributer as well. Thanks and let me know if you have any questions.

**Comment by EastDesire** [comment]
Sorry for the long delay @evgenjion , it's only now, after 4 years, that I can look into pull requests.

Though it's a nice idea, I think making the palette darker would actually be confusing for many users. For example, if the initial color was black, the palette would be completely black too. The way it is now, the user can always see the preview of their chosen color in the input field as well as a whole spectrum of available colors.

**Pull request closed without merging**
