### PR TITLE
Increase zIndex to fix issue with Bootstrap modal

### PR DESCRIPTION
**Pull request by georgecoca**
I've increased the zIndex property in order to play well with other layers which also has zIndex like Bootstrap Modal which has 1050. I think 9999 should be good enough.

### CODE REVIEW

**Comment by xseano** [comment]
In an effort to bring back and expand this brilliant library created by EastDesire, I created [PaletteJS](https://github.com/xseano/PaletteJS). If it is not too much trouble, would you mind submitting this PR to PaletteJS? Please let me know if you would like to be added as a contributer as well. Thanks and let me know if you have any questions.

**Comment by Coder-rks** [comment]
On clicking  input box the color panel popover. How is it possible that the color panel already focused when the page is loaded? i.e no need to click on the input box.

**Comment by EastDesire** [comment]
Sorry for the LONG delay. The question is where to draw the line with default z-index value. It originally used to be 100, then I think 500. Now it's 1000. Should we keep increasing it when other CSS frameworks show up that use higher z-index?

**Comment by EastDesire** [comment]
Increased z-index to 5000 in version 2.2.1. That's my highest bid.

**Pull request closed without merging**
