### PR TITLE
enterpriselicense_link_broken

### PR DESCRIPTION
**Pull request by geekskunk**
Trying to purchase enterprise license, but this link isn't working: http://jscolor.com/license/?type=org
(Please advise what to do.)

### CODE REVIEW

**Comment by Frazer** [comment]
Geekskunk, did you ever hear anything back about this?

**Comment by geekskunk** [comment]
@Frazer No, did not hear anything back on this.

**Comment by Frazer** [comment]
@geekskunk we finally got through to @EastDesire  and they sent us a link to buy the license, and it looks like they have also put the working links on the download page of the jscolor website.

**Comment by EastDesire** [comment]
Yes, it was fixed. Sorry for being unreachable here on GitHub for so long.

**Pull request closed without merging**
